### ISSUE TITLE
HP is splitting into 2 businesses - Servers are no longer provided by hp.com

### ISSUE THREAD

**Issue by nonfant** [dotps1/HPWarranty#9] opened 2015-08-06 21:34 UTC
When requesting the warranty status of a server I get the following error in the output xml file:
    <EIAError xsi:type="EIAError" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <TimeStamp>2015-08-06T21:22:36.417</TimeStamp>
      <ErrorLevel>FUNCTIONAL</ErrorLevel>
      <ErrorID>214</ErrorID>
      <ErrorText>Product or part not eligible for warranty</ErrorText>
      <ErrorClass>DataNotFound</ErrorClass>
      <DataPayLoad>Source WARRANTY SWOP 2016: This product is not
                eligible for HP Inc warranty; Support is obtained from
                Hewlett Packard Enterprise         . [TXID 6636151563]</DataPayLoad>
    </EIAError>

I am unsure what website/api the new HP Enterprise has however would it be possible to modify the cmdlets to allow the pulling of Server warranties again.

**Comment by beanska** [comment] 2015-08-06 21:36
Is this an enterprise or consumer model? What is the model name?

**Comment by nonfant** [comment] 2015-08-06 21:38
Enterprise - Server ProLiant DL380 G6 -SerialNumber "2UX93205MG" -ProductModel "491315-001"

**Comment by nonfant** [comment] 2015-08-06 22:00
Also I have around 100 that I used to check on a regular bases and it worked perfectly until 6/28. That's when it started failing. (just noticed it now)

**Comment by nonfant** [comment] 2015-08-06 22:10
I think I found the URL. When I go to the old warranty check system on HP.com. I am told to go here to check for Enterprise warranties:
http://h20566.www2.hpe.com/hpsc/wc/public/home

**Comment by dotps1** [comment] 2015-08-07 17:10
I'm not sure how to address this as of yet.  This module uses HP ISEE to handing the requests.  I will do some research when I get some time, I will let you know.  Thanks for the heads up.

**Comment by powershellpr0mpt** [comment] 2015-08-26 10:45
Hey Thomas,
As I had mentioned on twitter, I'm getting the current results when running a query:

Name                           Value
----                           -----
GracePeriod
ProductID                      <productmodel>
WarrantyDeterminationDescri...
OverallWarrantyEndDate
OverallWarrantyStartDate
SerialNumber                   <serialnumer>
OverallContractEndDate
ActiveWarrantyEntitlement

So I get a token and gdid, but zero results.
If I do this manually, I get the result that the service is currently unavailable, so perhaps this has to do with the same thing.

Difference with other users is that I'm not actually getting an error, just blank output.

**Comment by nonfant** [comment] 2015-08-26 11:15
The error is only seen in the XML output. You can enable the xml file output through one of the command parameters. I also only receive empty values when I run it just like you.
Thanks,Andreas


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by dotps1** [comment] 2015-08-26 12:50
Well, it actually seems like they have shut this service down entirely.  here is the return response I am getting from the HP ISEE:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<ns1:ISEE-GetOOSEntitlementInfoResponse schemaVersion="5.00" xmlns:ns1="http://www.hp.com/schemas/isee/5.00/entitlement">
  <Data frame="0" serialNumber="SerialNumber">
    <EIAError xsi:type="EIAError" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <TimeStamp>2015-08-26T12:45:06.751</TimeStamp>
      <ErrorLevel>FUNCTIONAL</ErrorLevel>
      <ErrorID>214</ErrorID>
      <ErrorText>Product or part not eligible for warranty</ErrorText>
      <ErrorClass>DataNotFound</ErrorClass>
      <DataPayLoad>Source WARRANTY SWOP 2016: This product is not
                eligible for HP Enterprise warranty; Support is obtained
                from HP Inc                             . [TXID 6647413557]</DataPayLoad>
    </EIAError>
  </Data>
</ns1:ISEE-GetOOSEntitlementInfoResponse>
```

Not sure what to say about this, until I have some time to really dig in and see what I can do about it.  my guess is they have completely changed how the requests work.

sorry everyone.

**Comment by powershellpr0mpt** [comment] 2015-08-26 17:32
No apologies required, this isn't an issue caused by you whatsoever.
Such a shame I only came to find out about this module now, could've really used the service.
I'll go check with a friend of mine [premium HP partner] what kind of system they use for warranty checks.

Thanks for the quick response!

**Comment by dotps1** [comment] 2015-08-26 18:24
if you can get me the new URLs for there ISEE, if they are still using it, it would be great!  thanks!

**Comment by powershellpr0mpt** [comment] 2015-08-27 10:50
Small update, checked with friend of mine and he says they're just using the HPE version of the tool
http://h20564.www2.hpe.com/hpsc/wc/public/home?lang=en-us&cc=us

So I just tried the module again and I'm getting info!

**Comment by dotps1** [comment] 2015-08-27 12:16
I like the idea, the issue is that this uses HP ISEE, and those URLs are public manual places to search.  They will not work in this module, I'm hoping HP will publish something for the API for the ISEE, but I have not seen anything as of yet.

Thanks for all the info.

**Comment by powershellpr0mpt** [comment] 2015-08-27 12:43
So unless they provide an ISCE [Instant Support Consumer Edition for example], there's no way to get the info for desktops :'(

**Comment by dotps1** [comment] 2015-08-27 12:54
seeming that way, is the module working for servers currently?  I don't have any HP Server info to try it out with.

**Comment by powershellpr0mpt** [comment] 2015-08-27 13:06
Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
GracePeriod                    30                                                                                                                                                             
ProductID                      ######                                                                                                                                                     
WarrantyDeterminationDescri... Ship date                                                                                                                                                      
OverallWarrantyEndDate         2013-07-30                                                                                                                                                     
OverallWarrantyStartDate       2010-07-01                                                                                                                                                     
SerialNumber                   ########                                                                                                                                                     
OverallContractEndDate                                                                                                                                                                        
ActiveWarrantyEntitlement      false

**Comment by dotps1** [comment] 2015-08-27 13:22
its that for a server?

**Comment by powershellpr0mpt** [comment] 2015-08-27 13:25
yes!

**Comment by dotps1** [comment] 2015-08-27 13:43
well, that's funning because this issue was opened for the opposite lol!  thanks for all the info!

**Comment by powershellpr0mpt** [comment] 2015-08-27 13:45
The whole thing got problematic because they started splitting databases it seems, because if you enter desktop details on the enterprise site it says invalid details and visa versa.

Then when I joined the party the entire service seemed to be down completely [I'm guessing due to doing the final switch to production]...

Now the services are up with separate databases, but this means you can no longer mass query desktop warranty..  :'(

**Comment by dotps1** [comment] 2015-08-27 14:59
Due to the name of this ticket, and it actually works, I am going to close this ticket and open a new one for workstations.  Thanks for all the help and info everyone!

**Closed by dotps1** 2015-08-27 14:59 UTC
