### ISSUE TITLE
Write-error

### ISSUE THREAD

**Issue by jimmy6154** [dotps1/HPWarranty#25] opened 2016-03-23 16:16 UTC
I'm getting this error. Not sure if its local to me and don't know how to get around it. Any help is appreciated.

PS P:\> Get-HPIncWarrantyEntitlement -ProductNumber 'A2K86ET#UUW' -SerialNumber
'CZC3151FJ3' -CountryCode SE
Get-HPIncWarrantyEntitlement :
At line:1 char:1
+ Get-HPIncWarrantyEntitlement -ProductNumber 'A2K86ET#UUW' -SerialNumb ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : 111,Get-HPIncWarrantyEntitlement

PS P:\>

**Comment by dotps1** [comment] 2016-03-27 00:37
sorry for the delay on this, been wrapped up in a few project.  I will look this in the morning.  my initial guess is the CountryCode param.  This was recently updated as HP keeps making this impossible to keep up with.

I will report back soon.  thanks.

**Comment by Oznero** [comment] 2016-04-08 14:03
Howdy, very impressive module that you've written.  I'm experiencing the same problem as jimmy.

**Comment by beanska** [comment] 2016-04-08 14:19
@Oznero Are you able to bring this URL up in a web browser from that same machine? 
[https://api-uns-sgw.external.hp.com/gw/hpit/egit/obligation.sa/1.1](https://api-uns-sgw.external.hp.com/gw/hpit/egit/obligation.sa/1.1)

**Comment by Oznero** [comment] 2016-04-08 16:25
Updated my code to reflect this repository.  It's working now.  Might want to update the powershellgallery module as well.  Nice work guys!

**Comment by dotps1** [comment] 2016-04-08 18:18
I actually have the module unlisted from the Gallery right now, so i'm not sure how you found it.

Once the issue is fixed for both servers and workstations, I will republish.  Thanks

**Comment by eligosfx** [comment] 2016-05-30 13:47
HI dotps1,

Great job.

I would like to ask you something about product number 
I have server with **654081-B21 ** and serial CZJ40704WG when I'm trying to run the script I getting error  
Get-HPIncWarrantyEntitlement -ProductNumber '654081-B21' -SerialNumber 'CZ3230S7EJ' -CountryCode IL
Get-HPIncWarrantyEntitlement : This product is not eligible for HP Inc warranty; Support is obtained from HEWLETT PACKARD ENTERPRISE         .
At line:2 char:1
+ Get-HPIncWarrantyEntitlement -ProductNumber '654081-B21' -SerialNumbe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-HPIncWarrantyEntitlement

if to use A2K86ET#UUW for product id , the script is running :+1: Get-HPIncWarrantyEntitlement -ProductNumber 'A2K86ET#UUW' -SerialNumber 'CZ3230S7EJ' -CountryCode IL


ComputerName                             : 
SerialNumber                             : CZ3230S7EJ
ProductNumber                            : A2K86ET#UUW
ProductLineDescription                   : 
ProductLineCode                          : 
ServiceObligationHardwareActiveIndicator : false
ServiceObligationStartDate               : 2012-08-01
ServiceObligationEndDate                 : 2015-08-30
DateSourceCode                           : 03
DateSourceDescription                    : Serial Number decode
WarrantyIdentifierCode                   : A015

**Comment by dotps1** [comment] 2016-05-30 14:08
thanks for the info, i will look more into this today.  but what is 654081-B21?

**Comment by eligosfx** [comment] 2016-05-30 14:21
The information on this page is an expanded detail for:
Product:	HP DL360p Gen8 8-SFF CTO Server
Serial number:	CZ3230S7EJ
Product number:	654081-B21

from:http://h20564.www2.hpe.com/hpsc/wc/public/viewDetails?index=0#1

how can i get the serial?

**Comment by dotps1** [comment] 2016-06-16 13:30
Fixed with merge from @beanska, this is NOT published on the gallery yet, i still need to get some Help written up and some more testing.  I also added PSCredential support for use with the $ComputerName parameter.

**Closed by dotps1** 2016-06-16 13:30 UTC
